# Generated by Django 3.0.7 on 2023-11-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20231107_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_photo_4',
            new_name='option',
        ),
    ]
